name: Student Branch Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  check-student-work:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Check if student created a new branch
        run: |
          if [ "${{ github.head_ref }}" == "main" ]; then
            echo "Error: You must create a new branch, not push directly to 'main'."
            exit 1
          fi
          echo "Branch ${GITHUB_HEAD_REF} successfully created."

      - name: Check for required phrase in the file
        run: |
          if ! grep -q "Make it pass" <file_name>; then
            echo "Error: 'Make it pass' not found in <file_name>"
            exit 1
          fi
          echo "'Make it pass' phrase found in <file_name>."

      - name: Check if student updated completed_students.txt
        run: |
          if ! grep -q "$GITHUB_ACTOR" completed_students.txt; then
            echo "Error: $GITHUB_ACTOR not found in completed_students.txt"
            exit 1
          fi
          echo "$GITHUB_ACTOR found in completed_students.txt"

      - name: Show progress of student
        run: |
          echo "Checking progress of $GITHUB_ACTOR."

      - name: Success
        run: echo "GitHub Workflow passed successfully."
